import { ArrowRight, CheckCircle2, Eye, EyeOff, ShieldCheck, Sparkles } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { ErroApi } from '../api'
import { usarAutenticacao } from '../autenticacao'
import AvisoEmailConfirmado from '../components/AvisoEmailConfirmado'
import { AssinaturaEmpresa } from '../components/RodapeEmpresa'
import { LinkInterno, Redirecionar, usarNavegacao } from '../roteamento'

export default function PaginaLogin(){
  const {user,login}=usarAutenticacao(); const navigate=usarNavegacao(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  if(user)return <Redirecionar to="/" replace/>
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{await login(email,password);navigate('/')}catch(err){setError(err instanceof ErroApi?err.message:'Não foi possível entrar.')}finally{setLoading(false)}}
  return <div className="login-page"><section className="login-hero"><div className="brand light"><div className="brand-mark"><img src="/cotapreco-icon.png" alt=""/></div><div><strong>CotaPreço</strong><span>Compras inteligentes</span></div></div><div className="hero-copy"><span className="eyebrow"><Sparkles size={16}/> Mais economia, menos planilhas</span><h1>Compare propostas.<br/>Compre melhor.</h1><p>Centralize suas cotações, receba preços dos distribuidores e encontre a melhor composição de compra em minutos.</p><ul><li><CheckCircle2/>Link simples para representantes</li><li><CheckCircle2/>Comparativo automático de preços</li><li><CheckCircle2/>Dados separados por farmácia</li></ul></div><div className="hero-security"><ShieldCheck/><span>Seus dados protegidos e isolados por empresa</span></div></section><section className="login-panel"><form className="login-card" onSubmit={submit}><AvisoEmailConfirmado/><div><span className="eyebrow green">Bem-vindo de volta</span><h2>Acesse sua conta</h2><p>Use suas credenciais para continuar.</p></div>{error&&<div className="alert alert-error">{error}</div>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Senha<div className="password-field"><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button type="button" aria-label={showPassword?'Ocultar senha':'Mostrar senha'} onClick={()=>setShowPassword(valor=>!valor)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label><LinkInterno className="forgot-password-link" to="/esqueci-senha">Esqueci minha senha</LinkInterno><button className="button button-primary button-large" disabled={loading}>{loading?'Entrando...':<>Entrar <ArrowRight size={19}/></>}</button><p className="login-alternative">Ainda não tem uma conta? <LinkInterno to="/cadastro">Cadastre sua farmácia</LinkInterno></p></form><AssinaturaEmpresa className="assinatura-empresa-login"/></section></div>
}
