import { PackagePlus, Plus, Search, X } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { api, ErroApi } from '../api'
import { EstadoVazio, AvisoErro, Carregando } from '../components/ComponentesUI'
import type { Produto } from '../types'

const initial={gtin:'',name:'',laboratory:'',presentation:'',category:'',active:true}
export default function PaginaProdutos(){
  const[products,setProducts]=useState<Produto[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[search,setSearch]=useState('');const[show,setShow]=useState(false);const[form,setForm]=useState(initial);const[saving,setSaving]=useState(false)
  const load=()=>api<Produto[]>('/products').then(setProducts).catch(e=>setError(e.message)).finally(()=>setLoading(false));useEffect(()=>{void load()},[])
  const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.gtin} ${p.laboratory??''}`.toLowerCase().includes(search.toLowerCase())),[products,search])
  const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await api('/products',{method:'POST',body:JSON.stringify(form)});setShow(false);setForm(initial);await load()}catch(e){setError(e instanceof ErroApi?e.message:'Não foi possível cadastrar.')}finally{setSaving(false)}}
  return <div className="page"><div className="page-header"><div><span className="eyebrow green">Catálogo</span><h1>Produtos</h1><p>Cadastre e consulte os itens usados nas cotações.</p></div><button className="button button-primary" onClick={()=>setShow(true)}><Plus/>Novo produto</button></div><div className="toolbar"><label className="search"><Search/><input placeholder="Buscar por nome, GTIN ou laboratório..." value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{error&&<AvisoErro message={error}/>} {loading?<Carregando/>:filtered.length===0?<EstadoVazio title="Nenhum produto cadastrado" description="Os produtos também são cadastrados automaticamente ao importar uma cotação." action={<button className="button button-primary" onClick={()=>setShow(true)}>Cadastrar produto</button>}/>:<div className="card table-card"><div className="table-wrap"><table><thead><tr><th>Produto</th><th>GTIN</th><th>Laboratório</th><th>Apresentação</th><th>Categoria</th><th>StatusCotacao</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td><code>{p.gtin}</code></td><td>{p.laboratory??'—'}</td><td>{p.presentation??'—'}</td><td>{p.category??'—'}</td><td><span className={`mini-tag ${p.active?'':'error'}`}>{p.active?'Ativo':'Inativo'}</span></td></tr>)}</tbody></table></div></div>}{show&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-header"><div className="modal-icon"><PackagePlus/></div><div><h2>Novo produto</h2><p>Preencha os dados principais do item.</p></div><button type="button" className="icon-button" onClick={()=>setShow(false)}><X/></button></div><div className="form-grid"><label>GTIN<input required inputMode="numeric" pattern="[0-9]{8,14}" value={form.gtin} onChange={e=>setForm({...form,gtin:e.target.value})}/></label><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Laboratório<input value={form.laboratory} onChange={e=>setForm({...form,laboratory:e.target.value})}/></label><label>Apresentação<input value={form.presentation} onChange={e=>setForm({...form,presentation:e.target.value})}/></label><label className="full">Categoria<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="button button-ghost" onClick={()=>setShow(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving?'Salvando...':'Cadastrar produto'}</button></div></form></div>}</div>
}
