import { ArrowLeft, CheckCircle2, Clipboard, Clock3, ExternalLink, Link2, Lock, PackageCheck, RefreshCw, Send, ShoppingCart, Users } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { api, ErroApi, date, money } from '../api'
import { EstadoVazio, AvisoErro, Carregando, EtiquetaStatus } from '../components/ComponentesUI'
import type { ComparacaoCotacao, Cotacao, RespostaCotacao } from '../types'
import { LinkInterno, usarParametros } from '../roteamento'

type Tab='products'|'responses'|'comparison'|'purchase'
export default function PaginaDetalheCotacao(){
  const{id}=usarParametros();const[quotation,setQuotation]=useState<Cotacao|null>(null);const[responses,setResponses]=useState<RespostaCotacao[]>([]);const[comparison,setComparison]=useState<ComparacaoCotacao|null>(null);const[tab,setTab]=useState<Tab>('products');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[copied,setCopied]=useState('')
  const load=useCallback(async()=>{if(!id)return;setLoading(true);setError('');try{const[q,r,c]=await Promise.all([api<Cotacao>(`/quotations/${id}`),api<RespostaCotacao[]>(`/quotations/${id}/responses`),api<ComparacaoCotacao>(`/quotations/${id}/comparison`)]);setQuotation(q);setResponses(r);setComparison(c)}catch(e){setError(e instanceof ErroApi?e.message:'Falha ao carregar a cotação.')}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load])
  const action=async(kind:'open'|'close')=>{setBusy(true);try{await api(`/quotations/${id}/${kind}`,{method:'POST'});await load()}catch(e){setError(e instanceof ErroApi?e.message:'Operação não concluída.')}finally{setBusy(false)}}
  const copy=async(value:string,type:string)=>{await navigator.clipboard.writeText(value);setCopied(type);setTimeout(()=>setCopied(''),1800)}
  if(loading)return <div className="page"><Carregando/></div>;if(!quotation)return <div className="page"><AvisoErro message={error||'Cotação não encontrada.'}/></div>
  const message=quotation.publicUrl?`Olá! Estamos realizando uma nova cotação.\nVocê pode enviar seus preços através do link abaixo:\n${quotation.publicUrl}\nObrigado!`:''
  return <div className="page"><div className="back-row"><LinkInterno to="/cotacoes" className="text-link"><ArrowLeft/>Voltar para cotações</LinkInterno></div><div className="detail-header"><div><div className="title-line"><h1>{quotation.name}</h1><EtiquetaStatus status={quotation.status}/></div><p>Criada em {date(quotation.createdAt)} · {quotation.items.length} produtos · Prazo: {date(quotation.expiresAt)}</p></div><div className="header-actions"><button className="button button-ghost" onClick={()=>void load()}><RefreshCw/>Atualizar</button>{quotation.status==='DRAFT'&&<button className="button button-primary" disabled={busy} onClick={()=>void action('open')}><Send/>Abrir cotação</button>}{quotation.status==='OPEN'&&<button className="button button-danger-soft" disabled={busy} onClick={()=>void action('close')}><Lock/>Fechar cotação</button>}</div></div>{error&&<AvisoErro message={error}/>} {quotation.publicUrl&&<section className="share-strip"><div><div className="share-strip-icon"><Link2/></div><div><strong>LinkInterno para representantes</strong><span>{quotation.publicUrl}</span></div></div><div><button className="button button-secondary" onClick={()=>void copy(quotation.publicUrl!,'link')}><Clipboard/>{copied==='link'?'Copiado!':'Copiar link'}</button><button className="button button-ghost" onClick={()=>void copy(message,'message')}>{copied==='message'?'Copiada!':'Copiar mensagem'}</button><a className="icon-button" title="Abrir link" href={quotation.publicUrl} target="_blank"><ExternalLink/></a></div></section>}
    <div className="tabs"><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}><PackageCheck/>Produtos <span>{quotation.items.length}</span></button><button className={tab==='responses'?'active':''} onClick={()=>setTab('responses')}><Users/>Respostas <span>{responses.filter(r=>r.status==='SUBMITTED').length}</span></button><button className={tab==='comparison'?'active':''} onClick={()=>setTab('comparison')}><CheckCircle2/>Comparativo</button><button className={tab==='purchase'?'active':''} onClick={()=>setTab('purchase')}><ShoppingCart/>Compra sugerida</button></div>
    {tab==='products'&&<section className="card"><div className="card-header"><div><h2>Produtos solicitados</h2><p>Lista de compra enviada aos representantes.</p></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Produto</th><th>GTIN</th><th>Laboratório</th><th>Quantidade</th></tr></thead><tbody>{quotation.items.map((item,i)=><tr key={item.id}><td>{i+1}</td><td><strong>{item.productName}</strong></td><td><code>{item.gtin}</code></td><td>{item.laboratory??'—'}</td><td><strong>{item.requestedQuantity}</strong> un.</td></tr>)}</tbody></table></div></section>}
    {tab==='responses'&&<section className="card"><div className="card-header"><div><h2>Respostas dos representantes</h2><p>Acompanhe quem já enviou os preços.</p></div></div>{responses.length===0?<EstadoVazio title="Nenhuma resposta ainda" description="Compartilhe o link acima com seus representantes."/>:<div className="table-wrap"><table><thead><tr><th>Distribuidora</th><th>Representante</th><th>Contato</th><th>StatusCotacao</th><th>Envio</th><th>Itens</th><th>Total</th></tr></thead><tbody>{responses.map(r=><tr key={r.id}><td><strong>{r.supplierName}</strong></td><td>{r.representativeName}</td><td>{r.phone}</td><td><EtiquetaStatus status={r.status}/></td><td>{r.submittedAt?date(r.submittedAt):<span className="muted"><Clock3/>Em andamento</span>}</td><td>{r.quotedItems} de {quotation.items.length}</td><td><strong>{money(r.total)}</strong></td></tr>)}</tbody></table></div>}</section>}
    {tab==='comparison'&&comparison&&<section className="card comparison-card"><div className="card-header"><div><h2>Comparativo de preços</h2><p>O menor preço disponível está destacado em cada linha.</p></div></div>{comparison.supplierTotals.length===0?<EstadoVazio title="Aguardando propostas" description="O comparativo será preenchido após o primeiro envio."/>:<div className="table-wrap"><table className="comparison-table"><thead><tr><th>Produto</th><th>Qtd.</th>{comparison.supplierTotals.map(s=><th key={s.responseId}>{s.supplierName}</th>)}<th>Melhor</th></tr></thead><tbody>{comparison.products.map(p=><tr key={p.quotationItemId}><td><strong>{p.productName}</strong><small>{p.gtin}</small></td><td>{p.requestedQuantity}</td>{comparison.supplierTotals.map(s=>{const o=p.offers.find(x=>x.responseId===s.responseId);return <td key={s.responseId} className={o?.bestPrice?'best-cell':''}>{o?<><strong>{money(o.unitPrice)}</strong><small>{o.availableQuantity} un.</small></>:<span className="dash">—</span>}</td>})}<td>{p.winningSupplier?<><strong className="green-text">{p.winningSupplier}</strong><small>{money(p.bestUnitPrice)}</small></>:<span className="dash">Sem oferta</span>}</td></tr>)}</tbody><tfoot><tr><td colSpan={2}><strong>Total por proposta</strong></td>{comparison.supplierTotals.map(s=><td key={s.responseId}><strong>{money(s.total)}</strong></td>)}<td/></tr></tfoot></table></div>}</section>}
    {tab==='purchase'&&comparison&&<div className="purchase-layout"><section className="card"><div className="card-header"><div><h2>Melhor composição de compra</h2><p>Distribuição que prioriza menor preço e quantidade disponível.</p></div></div>{comparison.suggestedPurchase.length===0?<EstadoVazio title="Ainda não há uma compra sugerida" description="Receba ao menos uma proposta para gerar a composição."/>:<><div className="supplier-cards">{comparison.suggestedPurchase.map(s=><div className="supplier-card" key={s.supplierName}><div className="supplier-initial">{s.supplierName[0]}</div><div><strong>{s.supplierName}</strong><span>{s.productCount} produtos · {s.totalQuantity} unidades</span></div><strong>{money(s.total)}</strong></div>)}</div><div className="composition-total"><span>Total sugerido</span><strong>{money(comparison.bestCompositionTotal)}</strong></div></>}</section><aside className="purchase-summary"><div className="summary-highlight"><ShoppingCart/><span>Compra sugerida</span><strong>{money(comparison.bestCompositionTotal)}</strong></div><div><span>Economia estimada</span><strong className="green-text">{money(comparison.estimatedSavings)}</strong></div><div><span>Produtos sem cotação</span><strong>{comparison.productsWithoutOffer}</strong></div><div><span>Quantidade insuficiente</span><strong>{comparison.partiallyCoveredProducts}</strong></div></aside></div>}
  </div>
}
