import { PackagePlus, Plus, Search, X } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { api, ErroApi } from '../api'
import { usarCamadaNoHistorico } from '../hooks/usarCamadaNoHistorico'
import { AvisoErro, Carregando, EstadoVazio } from '../components/ComponentesUI'
import type { Produto } from '../types'

const inicial={ean:'',name:'',laboratory:'',presentation:'',category:'',active:true}
export default function PaginaProdutos(){
  const[produtos,setProdutos]=useState<Produto[]>([]);const[busca,setBusca]=useState('');const[mostrar,setMostrar]=useState(false);const[formulario,setFormulario]=useState(inicial);const[erro,setErro]=useState('');const[carregando,setCarregando]=useState(true);const[salvando,setSalvando]=useState(false)
  const carregar=async()=>{try{setProdutos(await api<Produto[]>('/products'))}catch(e){setErro(e instanceof ErroApi?e.message:'Falha ao carregar produtos.')}finally{setCarregando(false)}}
  useEffect(()=>{void carregar()},[])
  const filtrados=useMemo(()=>produtos.filter(p=>`${p.name} ${p.ean??''} ${p.laboratory??''}`.toLowerCase().includes(busca.toLowerCase())),[produtos,busca])
  /* O voltar do navegador fecha o cadastro em vez de sair da lista de produtos. */
  usarCamadaNoHistorico(mostrar,()=>setMostrar(false))
  const enviar=async(evento:FormEvent)=>{evento.preventDefault();setSalvando(true);setErro('');try{await api('/products',{method:'POST',body:JSON.stringify({...formulario,ean:formulario.ean||null})});setMostrar(false);setFormulario(inicial);await carregar()}catch(e){setErro(e instanceof ErroApi?e.message:'Não foi possível cadastrar.')}finally{setSalvando(false)}}
  return <div className="page"><div className="page-header"><div><span className="eyebrow green">Catálogo</span><h1>Produtos</h1><p>Cadastre e consulte os itens usados nas cotações.</p></div><button className="button button-primary" onClick={()=>setMostrar(true)}><Plus/>Novo produto</button></div><div className="toolbar"><label className="search"><Search/><input placeholder="Buscar por nome, EAN ou laboratório..." value={busca} onChange={e=>setBusca(e.target.value)}/></label></div>{erro&&<AvisoErro message={erro}/>} {carregando?<Carregando/>:filtrados.length===0?<EstadoVazio title="Nenhum produto cadastrado" description="Os produtos também são cadastrados automaticamente ao importar uma cotação." action={<button className="button button-primary" onClick={()=>setMostrar(true)}>Cadastrar produto</button>}/>:<div className="card table-card"><div className="table-wrap"><table><thead><tr><th>Produto</th><th>EAN</th><th>Laboratório</th><th>Apresentação</th><th>Categoria</th><th>Status</th></tr></thead><tbody>{filtrados.map(produto=><tr key={produto.id}><td><strong>{produto.name}</strong></td><td>{produto.ean?<code>{produto.ean}</code>:<span className="muted">Não informado</span>}</td><td>{produto.laboratory??'—'}</td><td>{produto.presentation??'—'}</td><td>{produto.category??'—'}</td><td><span className={`mini-tag ${produto.active?'':'error'}`}>{produto.active?'Ativo':'Inativo'}</span></td></tr>)}</tbody></table></div></div>}{mostrar&&<div className="modal-backdrop"><form className="modal" onSubmit={enviar}><div className="modal-header"><div className="modal-icon"><PackagePlus/></div><div><h2>Novo produto</h2><p>Preencha os dados principais do item.</p></div><button type="button" className="icon-button" onClick={()=>setMostrar(false)}><X/></button></div><div className="form-grid"><label>EAN <small>Opcional</small><input inputMode="numeric" pattern="[0-9]{8,14}" value={formulario.ean} onChange={e=>setFormulario({...formulario,ean:e.target.value})}/></label><label>Nome<input required value={formulario.name} onChange={e=>setFormulario({...formulario,name:e.target.value})}/></label><label>Laboratório<input value={formulario.laboratory} onChange={e=>setFormulario({...formulario,laboratory:e.target.value})}/></label><label>Apresentação<input value={formulario.presentation} onChange={e=>setFormulario({...formulario,presentation:e.target.value})}/></label><label className="full">Categoria<input value={formulario.category} onChange={e=>setFormulario({...formulario,category:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="button button-ghost" onClick={()=>setMostrar(false)}>Cancelar</button><button className="button button-primary" disabled={salvando}>{salvando?'Salvando...':'Cadastrar produto'}</button></div></form></div>}</div>
}
