import { ArrowLeft, CheckCircle2, Eye, EyeOff, KeyRound, ShieldCheck } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { apiRepresentante, encerrarSessaoRepresentante, ErroApi } from '../api'
import { AvisoErro } from '../components/ComponentesUI'
import { IndicadorForcaSenha } from '../components/IndicadorForcaSenha'
import { LinkInterno, usarParametrosBusca } from '../roteamento'

export default function PaginaAlterarSenhaRepresentante(){
  const[params]=usarParametrosBusca();const retorno=params.get('retornar')?.startsWith('/cotacao/responder/')?params.get('retornar')!:'/';const[senhaAtual,setSenhaAtual]=useState('');const[novaSenha,setNovaSenha]=useState('');const[confirmacao,setConfirmacao]=useState('');const[mostrar,setMostrar]=useState(false);const[erro,setErro]=useState('');const[ocupado,setOcupado]=useState(false);const[concluido,setConcluido]=useState(false)
  const salvar=async(event:FormEvent)=>{event.preventDefault();setErro('');if(novaSenha!==confirmacao){setErro('A confirmação não corresponde à nova senha.');return}setOcupado(true);try{await apiRepresentante('/publico/representantes/senha',{method:'PUT',body:JSON.stringify({senhaAtual,novaSenha})});await encerrarSessaoRepresentante();setConcluido(true)}catch(e){setErro(e instanceof ErroApi?e.message:'Não foi possível alterar a senha.')}finally{setOcupado(false)}}
  return <div className="public-page public-center"><div className="public-logo reset-logo"><img className="cotapreco-logo" src="/cotapreco-logo.png?v=20260905-1" alt="CotaPreço"/></div><section className="public-card reset-card">{concluido?<><div className="success-icon large"><CheckCircle2/></div><h1>Senha alterada</h1><p>Por segurança, sua sessão foi encerrada. Entre novamente para continuar.</p><LinkInterno className="button button-primary button-large full-button" to={retorno}>Voltar para a cotação</LinkInterno></>:<><div className="success-icon small-icon"><KeyRound/></div><span className="eyebrow green">Conta do representante</span><h1>Alterar senha</h1><p>Confirme sua senha atual e escolha uma nova.</p>{erro&&<AvisoErro message={erro}/>}<form className="stack-form" onSubmit={salvar}><label>Senha atual<div className="password-field"><input required autoComplete="current-password" type={mostrar?'text':'password'} value={senhaAtual} onChange={e=>setSenhaAtual(e.target.value)}/><button type="button" aria-label={mostrar?'Ocultar senhas':'Mostrar senhas'} onClick={()=>setMostrar(valor=>!valor)}>{mostrar?<EyeOff/>:<Eye/>}</button></div></label><label>Nova senha<input required autoComplete="new-password" maxLength={72} type={mostrar?'text':'password'} value={novaSenha} onChange={e=>setNovaSenha(e.target.value)}/><IndicadorForcaSenha senha={novaSenha}/></label><label>Confirmar nova senha<input required autoComplete="new-password" maxLength={72} type={mostrar?'text':'password'} value={confirmacao} onChange={e=>setConfirmacao(e.target.value)}/></label><button className="button button-primary button-large full-button" disabled={ocupado}>{ocupado?'Atualizando...':'Atualizar senha'}</button></form></>}<div className="public-security"><ShieldCheck/>A alteração encerra as sessões ativas.</div>{!concluido&&<LinkInterno className="reset-back" to={retorno}><ArrowLeft/>Voltar para a cotação</LinkInterno>}</section></div>
}
