import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clipboard, FileSpreadsheet, Link2, UploadCloud, XCircle } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { api, ErroApi } from '../api'
import { AvisoErro } from '../components/ComponentesUI'
import type { PreviaImportacao, Cotacao } from '../types'
import { LinkInterno, usarNavegacao } from '../roteamento'

export default function PaginaNovaCotacao(){
  const navegar=usarNavegacao();const[etapa,setEtapa]=useState(1);const[nome,setNome]=useState('');const[prazo,setPrazo]=useState('');const[previa,setPrevia]=useState<PreviaImportacao|null>(null);const[cotacao,setCotacao]=useState<Cotacao|null>(null);const[erro,setErro]=useState('');const[ocupado,setOcupado]=useState(false);const[copiado,setCopiado]=useState('')
  const importar=async(arquivo:File)=>{setErro('');setOcupado(true);const corpo=new FormData();corpo.append('file',arquivo);try{setPrevia(await api<PreviaImportacao>('/quotations/import/preview',{method:'POST',body:corpo}));setEtapa(3)}catch(e){setErro(e instanceof ErroApi?e.message:'Falha ao importar o arquivo.')}finally{setOcupado(false)}}
  const criar=async()=>{if(!previa||previa.invalidRows>0)return;setOcupado(true);setErro('');try{const rascunho=await api<Cotacao>('/quotations',{method:'POST',body:JSON.stringify({name:nome,expiresAt:prazo?new Date(prazo).toISOString():null,items:previa.lines.filter(l=>l.valid).map(l=>({ean:l.ean,productName:l.productName,quantity:l.quantity}))})});setCotacao(await api<Cotacao>(`/quotations/${rascunho.id}/open`,{method:'POST'}));setEtapa(5)}catch(e){setErro(e instanceof ErroApi?e.message:'Não foi possível criar a cotação.')}finally{setOcupado(false)}}
  const copiar=async(valor:string,tipo:string)=>{await navigator.clipboard.writeText(valor);setCopiado(tipo);setTimeout(()=>setCopiado(''),1800)}
  const mensagem=cotacao?.publicUrl?`Olá! Estamos realizando uma nova cotação.\nVocê pode enviar seus preços através do link abaixo:\n${cotacao.publicUrl}\nObrigado!`:''
  return <div className="page narrow"><div className="back-row"><LinkInterno to="/cotacoes" className="text-link"><ArrowLeft/>Voltar para cotações</LinkInterno></div><div className="page-header"><div><span className="eyebrow green">Novo processo</span><h1>Nova cotação</h1><p>Em poucos passos, sua cotação estará pronta para compartilhar.</p></div></div><div className="stepper">{['Informações','Planilha','Revisão','Criação','Compartilhar'].map((rotulo,indice)=>{const numero=indice+1;return <div key={rotulo} className={`step ${etapa===numero?'active':''} ${etapa>numero?'done':''}`}><span>{etapa>numero?<Check size={16}/>:numero}</span><label>{rotulo}</label></div>})}</div>{erro&&<AvisoErro message={erro}/>}<section className="card wizard-card">
    {etapa===1&&<form onSubmit={(e:FormEvent)=>{e.preventDefault();setEtapa(2)}}><div className="wizard-heading"><span>Etapa 1 de 5</span><h2>Vamos identificar esta cotação</h2><p>Use um nome fácil de reconhecer no painel.</p></div><div className="form-grid"><label className="full">Nome da cotação<input autoFocus required maxLength={180} placeholder="Ex.: Reposição primeira quinzena" value={nome} onChange={e=>setNome(e.target.value)}/></label><label className="full">Prazo para respostas <small>Opcional</small><input type="datetime-local" value={prazo} min={new Date().toISOString().slice(0,16)} onChange={e=>setPrazo(e.target.value)}/></label></div><div className="wizard-actions"><span/><button className="button button-primary">Continuar <ArrowRight/></button></div></form>}
    {etapa===2&&<div><div className="wizard-heading"><span>Etapa 2 de 5</span><h2>Importe sua lista de compras</h2><p>A planilha deve ter EAN opcional, produto e quantidade.</p></div><label className={`dropzone ${ocupado?'disabled':''}`}><UploadCloud/><strong>{ocupado?'Processando planilha...':'Arraste ou selecione uma planilha'}</strong><span>Arquivos CSV ou XLSX de até 10 MB</span><input type="file" accept=".csv,.xlsx" disabled={ocupado} onChange={e=>{const arquivo=e.target.files?.[0];if(arquivo)void importar(arquivo)}}/></label><div className="file-example"><FileSpreadsheet/><div><strong>Formato esperado</strong><code>ean,produto,quantidade</code></div></div><div className="wizard-actions"><button className="button button-ghost" onClick={()=>setEtapa(1)}><ArrowLeft/>Voltar</button><span/></div></div>}
    {etapa===3&&previa&&<div><div className="wizard-heading"><span>Etapa 3 de 5</span><h2>Revise os produtos importados</h2><p>Nenhuma linha inválida será salva.</p></div><div className="import-summary"><div><CheckCircle2/><strong>{previa.validRows}</strong><span>linhas válidas</span></div><div className={previa.invalidRows?'danger':''}><XCircle/><strong>{previa.invalidRows}</strong><span>com problema</span></div><div><Clipboard/><strong>{previa.lines.filter(l=>!l.productExists&&l.valid).length}</strong><span>novos produtos</span></div></div><div className="table-wrap import-table"><table><thead><tr><th>Linha</th><th>EAN</th><th>Produto</th><th>Qtd.</th><th>Cadastro</th></tr></thead><tbody>{previa.lines.map(linha=><tr key={linha.row} className={!linha.valid?'invalid-row':''}><td>{linha.row}</td><td>{linha.ean?<code>{linha.ean}</code>:<span className="muted">Sem EAN</span>}</td><td><strong>{linha.productName||'Sem nome'}</strong>{linha.errors.map(x=><small className="field-error" key={x}>{x}</small>)}</td><td>{linha.quantity??'—'}</td><td>{linha.valid?<span className={`mini-tag ${linha.productExists?'':'new'}`}>{linha.productExists?'Encontrado':'Será cadastrado'}</span>:<span className="mini-tag error">Corrigir</span>}</td></tr>)}</tbody></table></div>{previa.invalidRows>0&&<div className="alert alert-warning">Corrija as linhas destacadas na planilha e importe novamente.</div>}<div className="wizard-actions"><button className="button button-ghost" onClick={()=>setEtapa(2)}><ArrowLeft/>Trocar arquivo</button><button className="button button-primary" disabled={previa.invalidRows>0} onClick={()=>setEtapa(4)}>Revisar criação <ArrowRight/></button></div></div>}
    {etapa===4&&previa&&<div><div className="wizard-heading"><span>Etapa 4 de 5</span><h2>Tudo pronto para abrir</h2><p>Ao confirmar, produtos novos serão cadastrados e o link público será gerado.</p></div><div className="review-box"><div><span>Nome</span><strong>{nome}</strong></div><div><span>Prazo</span><strong>{prazo?new Date(prazo).toLocaleString('pt-BR'):'Sem prazo definido'}</strong></div><div><span>Produtos</span><strong>{previa.validRows} itens</strong></div><div><span>Novos cadastros</span><strong>{previa.lines.filter(l=>!l.productExists).length} produtos</strong></div></div><div className="wizard-actions"><button className="button button-ghost" onClick={()=>setEtapa(3)}><ArrowLeft/>Voltar</button><button className="button button-primary" disabled={ocupado} onClick={()=>void criar()}>{ocupado?'Criando...':'Criar e abrir cotação'} <Check/></button></div></div>}
    {etapa===5&&cotacao?.publicUrl&&<div className="share-success"><div className="success-icon"><CheckCircle2/></div><span className="eyebrow green">Cotação aberta</span><h2>Agora é só compartilhar!</h2><p>Envie este link para os representantes. Eles entram ou criam uma conta para responder.</p><div className="copy-box"><Link2/><span>{cotacao.publicUrl}</span><button className="button button-secondary" onClick={()=>void copiar(cotacao.publicUrl!,'link')}>{copiado==='link'?'Copiado!':'Copiar link'}</button></div><div className="message-preview"><p>{mensagem}</p><button className="button button-ghost" onClick={()=>void copiar(mensagem,'mensagem')}><Clipboard/>{copiado==='mensagem'?'Mensagem copiada!':'Copiar mensagem'}</button></div><div className="wizard-actions centered"><button className="button button-primary" onClick={()=>navegar(`/cotacoes/${cotacao.id}`)}>Acompanhar cotação <ArrowRight/></button></div></div>}
  </section></div>
}
