import { Plus, ShieldCheck, UserRound, Users } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { api, ErroApi } from '../api'
import { usarAutenticacao } from '../autenticacao'
import { AvisoErro, Carregando } from '../components/ComponentesUI'
import type { UsuarioAdministracao } from '../types'

const perfis={ADMIN:'Administrador',BUYER:'Comprador',VIEWER:'Visualizador'} as const

export default function PaginaUsuarios(){
  const {user}=usarAutenticacao(); const [usuarios,setUsuarios]=useState<UsuarioAdministracao[]|null>(null); const [erro,setErro]=useState(''); const [mensagem,setMensagem]=useState(''); const [mostrarForm,setMostrarForm]=useState(false); const [nome,setNome]=useState(''); const [email,setEmail]=useState(''); const [senha,setSenha]=useState(''); const [perfil,setPerfil]=useState<UsuarioAdministracao['role']>('BUYER'); const [ocupado,setOcupado]=useState(false)
  const carregar=()=>api<UsuarioAdministracao[]>('/users').then(setUsuarios).catch(e=>setErro(e instanceof ErroApi?e.message:'Não foi possível carregar os usuários.'))
  useEffect(()=>{if(user?.role==='ADMIN')carregar()},[user?.role])
  const criar=async(event:FormEvent)=>{event.preventDefault();setErro('');setMensagem('');setOcupado(true);try{const criado=await api<UsuarioAdministracao>('/users',{method:'POST',body:JSON.stringify({nome,email,senha,perfil})});setUsuarios(atual=>[...(atual??[]),criado].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')));setNome('');setEmail('');setSenha('');setPerfil('BUYER');setMostrarForm(false);setMensagem(`${criado.name} já pode acessar a farmácia.`)}catch(e){setErro(e instanceof ErroApi?e.message:'Não foi possível criar o usuário.')}finally{setOcupado(false)}}
  if(user?.role!=='ADMIN')return <div className="page"><AvisoErro message="Somente administradores podem gerenciar usuários."/></div>
  if(!usuarios)return <div className="page"><Carregando/>{erro&&<AvisoErro message={erro}/>}</div>
  return <div className="page"><div className="page-header"><div><span className="eyebrow green">Administração</span><h1>Usuários</h1><p>Controle quem pode acessar a conta da sua farmácia.</p></div><button className="button button-primary" onClick={()=>{setErro('');setMensagem('');setMostrarForm(true)}}><Plus/>Novo usuário</button></div>{mensagem&&<div className="alert alert-success">{mensagem}</div>}{erro&&!mostrarForm&&<AvisoErro message={erro}/>}<section className="card"><div className="card-header"><div><h2><Users/> Equipe da farmácia</h2><p>{usuarios.length} usuário{usuarios.length!==1?'s':''} com acesso.</p></div></div>{usuarios.length===0?<div className="empty-users"><UserRound/><strong>Nenhum usuário cadastrado</strong><span>Crie o primeiro acesso para sua equipe.</span></div>:<div className="table-wrap"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Status</th><th>Cadastro</th></tr></thead><tbody>{usuarios.map(u=><tr key={u.id}><td><div className="user-cell"><div className="avatar small">{u.name.slice(0,2).toUpperCase()}</div><div><strong>{u.name}</strong><span>{u.email}</span></div></div></td><td><span className={`role-tag role-${u.role.toLowerCase()}`}>{u.role==='ADMIN'&&<ShieldCheck/>}{perfis[u.role]}</span></td><td><span className={u.active?'status-active':'status-inactive'}>{u.active?'Ativo':'Inativo'}</span></td><td>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(u.createdAt))}</td></tr>)}</tbody></table></div>}</section>{mostrarForm&&<div className="modal-backdrop" role="presentation"><form className="modal user-modal" onSubmit={criar}><div className="modal-header"><div className="modal-icon"><UserRound/></div><div><h2>Novo usuário</h2><p>O acesso será criado para esta farmácia.</p></div><button type="button" className="icon-button" onClick={()=>setMostrarForm(false)}>×</button></div>{erro&&<AvisoErro message={erro}/>}<div className="user-form"><label>Nome<input value={nome} onChange={e=>setNome(e.target.value)} autoComplete="name" maxLength={120} required/></label><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" maxLength={180} required/></label><label>Perfil<select value={perfil} onChange={e=>setPerfil(e.target.value as UsuarioAdministracao['role'])}><option value="BUYER">Comprador — cria e edita cotações</option><option value="VIEWER">Visualizador — somente consulta</option><option value="ADMIN">Administrador — gerencia conta e equipe</option></select></label><label>Senha inicial<input type="password" value={senha} onChange={e=>setSenha(e.target.value)} autoComplete="new-password" minLength={8} required/><small>No mínimo 8 caracteres.</small></label></div><div className="modal-actions"><button type="button" className="button button-ghost" onClick={()=>setMostrarForm(false)}>Cancelar</button><button className="button button-primary" disabled={ocupado}>{ocupado?'Criando...':'Criar usuário'}</button></div></form></div>}</div>
}
