import { Eye, EyeOff, KeyRound, Save } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { api, ErroApi } from '../api'
import { AvisoErro } from '../components/ComponentesUI'

export default function PaginaAlterarSenha(){
  const[senhaAtual,setSenhaAtual]=useState('');const[novaSenha,setNovaSenha]=useState('');const[confirmacao,setConfirmacao]=useState('');const[mostrar,setMostrar]=useState(false);const[erro,setErro]=useState('');const[mensagem,setMensagem]=useState('');const[ocupado,setOcupado]=useState(false)
  const salvar=async(event:FormEvent)=>{event.preventDefault();setErro('');setMensagem('');if(novaSenha!==confirmacao){setErro('A confirmação não corresponde à nova senha.');return}setOcupado(true);try{await api('/auth/password',{method:'PUT',body:JSON.stringify({senhaAtual,novaSenha})});setSenhaAtual('');setNovaSenha('');setConfirmacao('');setMensagem('Senha atualizada com sucesso.')}catch(e){setErro(e instanceof ErroApi?e.message:'Não foi possível alterar a senha.')}finally{setOcupado(false)}}
  return <div className="page"><div className="page-header"><div><span className="eyebrow green">Minha conta</span><h1>Alterar senha</h1><p>Atualize a senha usada para acessar o CotaPreço.</p></div></div><section className="card settings-card"><div className="card-header"><div><h2><KeyRound/> Segurança da conta</h2><p>Informe a senha atual para confirmar a alteração.</p></div></div><form className="stack-form settings-form" onSubmit={salvar}>{erro&&<AvisoErro message={erro}/>} {mensagem&&<div className="alert alert-success">{mensagem}</div>}<label>Senha atual<div className="password-field"><input required autoComplete="current-password" type={mostrar?'text':'password'} value={senhaAtual} onChange={e=>setSenhaAtual(e.target.value)}/><button type="button" aria-label={mostrar?'Ocultar senhas':'Mostrar senhas'} onClick={()=>setMostrar(v=>!v)}>{mostrar?<EyeOff/>:<Eye/>}</button></div></label><label>Nova senha<input required minLength={8} maxLength={72} autoComplete="new-password" type={mostrar?'text':'password'} value={novaSenha} onChange={e=>setNovaSenha(e.target.value)}/><small>Use pelo menos 8 caracteres.</small></label><label>Confirmar nova senha<input required minLength={8} maxLength={72} autoComplete="new-password" type={mostrar?'text':'password'} value={confirmacao} onChange={e=>setConfirmacao(e.target.value)}/></label><button className="button button-primary" disabled={ocupado}><Save/>{ocupado?'Atualizando...':'Atualizar senha'}</button></form></section></div>
}
