import { ArrowRight, ClipboardCheck, ClipboardList, CircleDollarSign, PiggyBank, Plus } from 'lucide-react'
import { date, money } from '../api'
import { usarAutenticacao } from '../autenticacao'
import { EstadoVazio, AvisoErro, EtiquetaStatus } from '../components/ComponentesUI'
import { usarPainel } from '../hooks/usarPainel'
import { LinkInterno } from '../roteamento'

export default function PaginaPainel(){
  const {user}=usarAutenticacao(); const {data,carregando,revalidando,erro,recarregar}=usarPainel(user)
  return <div className="page" aria-busy={carregando||revalidando}><div className="page-header"><div><span className="eyebrow green">Visão geral</span><h1>Olá, {user?.name.split(' ')[0]}!</h1><p>Acompanhe suas cotações e oportunidades de economia.</p></div><LinkInterno className="button button-primary" to="/cotacoes/nova"><Plus/>Nova cotação</LinkInterno></div>{revalidando&&data&&<div className="dashboard-update-status" role="status">Atualizando dados do painel…</div>}{erro&&data&&<div className="dashboard-update-status dashboard-update-error" role="status">Não foi possível atualizar agora. Os últimos dados continuam visíveis. <button type="button" onClick={()=>void recarregar()}>Tentar novamente</button></div>}{erro&&!data&&<div className="dashboard-load-error"><AvisoErro message={erro}/><button className="button button-secondary" type="button" onClick={()=>void recarregar()}>Tentar novamente</button></div>}{!data&&carregando?<PainelSkeleton/>:data&&<><div className="stats-grid"><Stat icon={<ClipboardList/>} label="Cotações abertas" value={String(data.openQuotations)} tone="green"/><Stat icon={<ClipboardCheck/>} label="Cotações finalizadas" value={String(data.finishedQuotations)} tone="blue"/><Stat icon={<CircleDollarSign/>} label="Respostas no mês" value={String(data.responsesThisMonth)} tone="amber"/><Stat icon={<PiggyBank/>} label="Economia estimada" value={money(data.estimatedSavings)} tone="purple" hint="Diferença para a segunda melhor oferta, considerando somente quantidades comparáveis."/></div><section className="card"><div className="card-header"><div><h2>Últimas cotações</h2><p>Atividade recente da sua farmácia</p></div><LinkInterno className="text-link" to="/cotacoes">Ver todas <ArrowRight/></LinkInterno></div>{data.latestQuotations.length===0?<EstadoVazio title="Sua primeira cotação começa aqui" description="Importe uma lista e compartilhe o link com seus distribuidores." action={<LinkInterno className="button button-primary" to="/cotacoes/nova">Criar cotação</LinkInterno>}/>:<div className="table-wrap"><table><thead><tr><th>Cotação</th><th>Data</th><th>Produtos</th><th>Respostas</th><th>StatusCotacao</th><th/></tr></thead><tbody>{data.latestQuotations.map(q=><tr key={q.id}><td><strong>{q.name}</strong></td><td>{date(q.createdAt)}</td><td>{q.productCount}</td><td><strong className="green-text">{q.submittedResponses} recebida{q.submittedResponses!==1?'s':''}</strong></td><td><EtiquetaStatus status={q.status}/></td><td><LinkInterno className="row-link" to={`/cotacoes/${q.id}`}><ArrowRight/></LinkInterno></td></tr>)}</tbody></table></div>}</section></>}</div>
}
function Stat({icon,label,value,tone,hint}:{icon:React.ReactNode;label:string;value:string;tone:string;hint?:string}){return <div className="stat-card" title={hint}><div className={`stat-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}

function PainelSkeleton(){
  const cards=[{icon:<ClipboardList/>,label:'Cotações abertas',tone:'green'},{icon:<ClipboardCheck/>,label:'Cotações finalizadas',tone:'blue'},{icon:<CircleDollarSign/>,label:'Respostas no mês',tone:'amber'},{icon:<PiggyBank/>,label:'Economia estimada',tone:'purple'}]
  return <><span className="sr-only" role="status">Carregando dados do painel.</span><div className="stats-grid" aria-hidden="true">{cards.map(card=><div className="stat-card" key={card.label}><div className={`stat-icon ${card.tone}`}>{card.icon}</div><div><span>{card.label}</span><span className="skeleton-block dashboard-skeleton-value"/></div></div>)}</div><section className="card dashboard-skeleton-table"><div className="card-header"><div><h2>Últimas cotações</h2><p>Atividade recente da sua farmácia</p></div><LinkInterno className="text-link" to="/cotacoes">Ver todas <ArrowRight/></LinkInterno></div><div className="table-wrap"><table><thead><tr><th>Cotação</th><th>Data</th><th>Produtos</th><th>Respostas</th><th>StatusCotacao</th><th/></tr></thead><tbody aria-hidden="true">{[0,1,2].map(linha=><tr key={linha}>{[42,30,18,28,22,8].map((largura,coluna)=><td key={coluna}><span className="skeleton-block dashboard-skeleton-cell" style={{width:`${largura}%`}}/></td>)}</tr>)}</tbody></table></div></section></>
}
