import { ArrowRight, Building2, CheckCircle2, ShieldCheck, Sparkles } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { ErroApi } from '../api'
import { usarAutenticacao } from '../autenticacao'
import { LinkInterno, Redirecionar, usarNavegacao } from '../roteamento'

export default function PaginaCadastroFarmacia(){
  const {user,cadastrarFarmacia}=usarAutenticacao(); const navigate=usarNavegacao()
  const [nomeUsuario,setNomeUsuario]=useState(''); const [nomeFarmacia,setNomeFarmacia]=useState(''); const [cnpj,setCnpj]=useState(''); const [email,setEmail]=useState(''); const [senha,setSenha]=useState(''); const [confirmacao,setConfirmacao]=useState(''); const [erro,setErro]=useState(''); const [ocupado,setOcupado]=useState(false)
  if(user)return <Redirecionar to="/" replace/>
  const cadastrar=async(event:FormEvent)=>{event.preventDefault();setErro('');if(senha!==confirmacao){setErro('As senhas não conferem.');return}setOcupado(true);try{await cadastrarFarmacia({nomeUsuario,nomeFarmacia,cnpj:cnpj.replace(/\D/g,''),email,senha});navigate('/')}catch(e){setErro(e instanceof ErroApi?e.message:'Não foi possível criar a conta.')}finally{setOcupado(false)}}
  return <div className="login-page registration-page"><section className="login-hero"><div className="brand light"><div className="brand-mark"><img src="/cotapreco-icon.png" alt=""/></div><div><strong>CotaPreço</strong><span>Compras inteligentes</span></div></div><div className="hero-copy"><span className="eyebrow"><Sparkles size={16}/> Comece em poucos minutos</span><h1>Sua farmácia,<br/>mais competitiva.</h1><p>Crie a conta da sua farmácia e convide sua equipe para centralizar as compras.</p><ul><li><CheckCircle2/>Você será o administrador da conta</li><li><CheckCircle2/>Inclua compradores e visualizadores depois</li><li><CheckCircle2/>Cada farmácia mantém seus dados isolados</li></ul></div><div className="hero-security"><ShieldCheck/><span>Seus dados protegidos e isolados por empresa</span></div></section><section className="login-panel"><form className="login-card registration-card" onSubmit={cadastrar}><div><span className="eyebrow green"><Building2 size={15}/> Nova conta</span><h2>Cadastre sua farmácia</h2><p>Crie o acesso do administrador da sua equipe.</p></div>{erro&&<div className="alert alert-error">{erro}</div>}<div className="registration-grid"><label>Seu nome<input value={nomeUsuario} onChange={e=>setNomeUsuario(e.target.value)} autoComplete="name" maxLength={120} required/></label><label>Nome da farmácia<input value={nomeFarmacia} onChange={e=>setNomeFarmacia(e.target.value)} maxLength={160} required/></label><label>CNPJ<input value={cnpj} onChange={e=>setCnpj(formatarCnpj(e.target.value))} inputMode="numeric" autoComplete="off" maxLength={18} required/></label><label>E-mail de acesso<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" maxLength={180} required/></label><label>Senha<input type="password" value={senha} onChange={e=>setSenha(e.target.value)} autoComplete="new-password" minLength={8} required/><small>No mínimo 8 caracteres.</small></label><label>Confirme a senha<input type="password" value={confirmacao} onChange={e=>setConfirmacao(e.target.value)} autoComplete="new-password" minLength={8} required/></label></div><button className="button button-primary button-large" disabled={ocupado}>{ocupado?'Criando conta...':<>Criar conta <ArrowRight size={19}/></>}</button><p className="login-alternative">Já possui acesso? <LinkInterno to="/login">Entrar na conta</LinkInterno></p></form></section></div>
}

function formatarCnpj(valor:string){const digitos=valor.replace(/\D/g,'').slice(0,14);return digitos.replace(/^(\d{2})(\d)/,'$1.$2').replace(/^(\d{2})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1/$2').replace(/(\d{4})(\d)/,'$1-$2')}
