import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clipboard, FileSpreadsheet, Link2, UploadCloud, XCircle } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { api, ErroApi } from '../api'
import { AvisoErro } from '../components/ComponentesUI'
import type { PreviaImportacao, Cotacao } from '../types'
import { LinkInterno, usarNavegacao } from '../roteamento'

export default function PaginaNovaCotacao(){
  const navigate=usarNavegacao();const[step,setStep]=useState(1);const[name,setName]=useState('');const[expiresAt,setExpiresAt]=useState('');const[preview,setPreview]=useState<PreviaImportacao|null>(null);const[quotation,setQuotation]=useState<Cotacao|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[copied,setCopied]=useState('')
  const upload=async(file:File)=>{setError('');setBusy(true);const body=new FormData();body.append('file',file);try{const result=await api<PreviaImportacao>('/quotations/import/preview',{method:'POST',body});setPreview(result);setStep(3)}catch(e){setError(e instanceof ErroApi?e.message:'Falha ao importar o arquivo.')}finally{setBusy(false)}}
  const create=async()=>{if(!preview||preview.invalidRows>0)return;setBusy(true);setError('');try{const draft=await api<Cotacao>('/quotations',{method:'POST',body:JSON.stringify({name,expiresAt:expiresAt?new Date(expiresAt).toISOString():null,items:preview.lines.filter(l=>l.valid).map(l=>({gtin:l.gtin,productName:l.productName,quantity:l.quantity}))})});const opened=await api<Cotacao>(`/quotations/${draft.id}/open`,{method:'POST'});setQuotation(opened);setStep(5)}catch(e){setError(e instanceof ErroApi?e.message:'Não foi possível criar a cotação.')}finally{setBusy(false)}}
  const copy=async(value:string,type:string)=>{await navigator.clipboard.writeText(value);setCopied(type);setTimeout(()=>setCopied(''),1800)}
  const message=quotation?.publicUrl?`Olá! Estamos realizando uma nova cotação.\nVocê pode enviar seus preços através do link abaixo:\n${quotation.publicUrl}\nObrigado!`:''
  return <div className="page narrow"><div className="back-row"><LinkInterno to="/cotacoes" className="text-link"><ArrowLeft/>Voltar para cotações</LinkInterno></div><div className="page-header"><div><span className="eyebrow green">Novo processo</span><h1>Nova cotação</h1><p>Em poucos passos, sua cotação estará pronta para compartilhar.</p></div></div><div className="stepper">{['Informações','Planilha','Revisão','Criação','Compartilhar'].map((label,index)=>{const n=index+1;return <div key={label} className={`step ${step===n?'active':''} ${step>n?'done':''}`}><span>{step>n?<Check size={16}/>:n}</span><label>{label}</label></div>})}</div>{error&&<AvisoErro message={error}/>}<section className="card wizard-card">
    {step===1&&<form onSubmit={(e:FormEvent)=>{e.preventDefault();setStep(2)}}><div className="wizard-heading"><span>Etapa 1 de 5</span><h2>Vamos identificar esta cotação</h2><p>Use um nome fácil de reconhecer no painel.</p></div><div className="form-grid"><label className="full">Nome da cotação<input autoFocus required maxLength={180} placeholder="Ex.: Reposição primeira quinzena" value={name} onChange={e=>setName(e.target.value)}/></label><label className="full">Prazo para respostas <small>Opcional</small><input type="datetime-local" value={expiresAt} min={new Date().toISOString().slice(0,16)} onChange={e=>setExpiresAt(e.target.value)}/></label></div><div className="wizard-actions"><span/><button className="button button-primary">Continuar <ArrowRight/></button></div></form>}
    {step===2&&<div><div className="wizard-heading"><span>Etapa 2 de 5</span><h2>Importe sua lista de compras</h2><p>O arquivo deve conter as colunas GTIN, produto e quantidade.</p></div><label className={`dropzone ${busy?'disabled':''}`}><UploadCloud/><strong>{busy?'Processando planilha...':'Arraste ou selecione uma planilha'}</strong><span>Arquivos CSV ou XLSX de até 10 MB</span><input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label><div className="file-example"><FileSpreadsheet/><div><strong>Formato esperado</strong><code>gtin,produto,quantidade</code></div></div><div className="wizard-actions"><button className="button button-ghost" onClick={()=>setStep(1)}><ArrowLeft/>Voltar</button><span/></div></div>}
    {step===3&&preview&&<div><div className="wizard-heading"><span>Etapa 3 de 5</span><h2>Revise os produtos importados</h2><p>Nenhuma linha inválida será salva.</p></div><div className="import-summary"><div><CheckCircle2/><strong>{preview.validRows}</strong><span>linhas válidas</span></div><div className={preview.invalidRows?'danger':''}><XCircle/><strong>{preview.invalidRows}</strong><span>com problema</span></div><div><Clipboard/><strong>{preview.lines.filter(l=>!l.productExists&&l.valid).length}</strong><span>novos produtos</span></div></div><div className="table-wrap import-table"><table><thead><tr><th>Linha</th><th>GTIN</th><th>Produto</th><th>Qtd.</th><th>Cadastro</th></tr></thead><tbody>{preview.lines.map(line=><tr key={line.row} className={!line.valid?'invalid-row':''}><td>{line.row}</td><td><code>{line.gtin||'—'}</code></td><td><strong>{line.productName||'Sem nome'}</strong>{line.errors.map(x=><small className="field-error" key={x}>{x}</small>)}</td><td>{line.quantity??'—'}</td><td>{line.valid?<span className={`mini-tag ${line.productExists?'':'new'}`}>{line.productExists?'Encontrado':'Será cadastrado'}</span>:<span className="mini-tag error">Corrigir</span>}</td></tr>)}</tbody></table></div>{preview.invalidRows>0&&<div className="alert alert-warning">Corrija as linhas destacadas na planilha e importe novamente. A cotação só será criada com a lista totalmente válida.</div>}<div className="wizard-actions"><button className="button button-ghost" onClick={()=>setStep(2)}><ArrowLeft/>Trocar arquivo</button><button className="button button-primary" disabled={preview.invalidRows>0} onClick={()=>setStep(4)}>Revisar criação <ArrowRight/></button></div></div>}
    {step===4&&preview&&<div><div className="wizard-heading"><span>Etapa 4 de 5</span><h2>Tudo pronto para abrir</h2><p>Ao confirmar, produtos novos serão cadastrados e o link público será gerado.</p></div><div className="review-box"><div><span>Nome</span><strong>{name}</strong></div><div><span>Prazo</span><strong>{expiresAt?new Date(expiresAt).toLocaleString('pt-BR'):'Sem prazo definido'}</strong></div><div><span>Produtos</span><strong>{preview.validRows} itens</strong></div><div><span>Novos cadastros</span><strong>{preview.lines.filter(l=>!l.productExists).length} produtos</strong></div></div><div className="wizard-actions"><button className="button button-ghost" onClick={()=>setStep(3)}><ArrowLeft/>Voltar</button><button className="button button-primary" disabled={busy} onClick={()=>void create()}>{busy?'Criando...':'Criar e abrir cotação'} <Check/></button></div></div>}
    {step===5&&quotation?.publicUrl&&<div className="share-success"><div className="success-icon"><CheckCircle2/></div><span className="eyebrow green">Cotação aberta</span><h2>Agora é só compartilhar!</h2><p>Envie este link para os representantes. Eles não precisam criar uma conta.</p><div className="copy-box"><Link2/><span>{quotation.publicUrl}</span><button className="button button-secondary" onClick={()=>void copy(quotation.publicUrl!,'link')}>{copied==='link'?'Copiado!':'Copiar link'}</button></div><div className="message-preview"><p>{message}</p><button className="button button-ghost" onClick={()=>void copy(message,'message')}><Clipboard/>{copied==='message'?'Mensagem copiada!':'Copiar mensagem'}</button></div><div className="wizard-actions centered"><button className="button button-primary" onClick={()=>navigate(`/cotacoes/${quotation.id}`)}>Acompanhar cotação <ArrowRight/></button></div></div>}
  </section></div>
}
