import { ArrowLeft, ArrowRight, Building2, Check, CheckCircle2, Clock3, PackageCheck, Save, Send, ShieldCheck, ShoppingBag } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { api, ErroApi, date, money } from '../api'
import { AvisoErro, Carregando } from '../components/ComponentesUI'
import type { CotacaoPublica, RespostaPublica, ItemRespostaPublica } from '../types'
import { usarParametros, usarParametrosBusca } from '../roteamento'

const emptyIdentity={representativeName:'',supplierName:'',phone:'',email:'',supplierDocument:''}
export default function PaginaRespostaPublica(){
  const{token=''}=usarParametros();const[params,setParams]=usarParametrosBusca();const[quotation,setQuotation]=useState<CotacaoPublica|null>(null);const[response,setResponse]=useState<RespostaPublica|null>(null);const[identity,setIdentity]=useState(emptyIdentity);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[review,setReview]=useState(false);const[saved,setSaved]=useState(false)
  useEffect(()=>{let active=true;const load=async()=>{try{const q=await api<CotacaoPublica>(`/public/quotations/${token}`);if(!active)return;setQuotation(q);const queryToken=params.get('resposta')||localStorage.getItem(`cotapreco_response_${token}`);if(queryToken){try{const r=await api<RespostaPublica>(`/public/responses/${queryToken}`);if(active){setResponse(r);if(!params.get('resposta'))setParams({resposta:queryToken},{replace:true})}}catch{localStorage.removeItem(`cotapreco_response_${token}`)}}}catch(e){if(active)setError(e instanceof ErroApi?e.message:'Cotação não encontrada.')}finally{if(active)setLoading(false)}};void load();return()=>{active=false}},[token,params,setParams])
  const start=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const result=await api<{responseToken:string}>(`/public/quotations/${token}/responses`,{method:'POST',body:JSON.stringify(identity)});localStorage.setItem(`cotapreco_response_${token}`,result.responseToken);setParams({resposta:result.responseToken},{replace:true});setResponse(await api<RespostaPublica>(`/public/responses/${result.responseToken}`))}catch(e){setError(e instanceof ErroApi?e.message:'Não foi possível iniciar.')}finally{setBusy(false)}}
  const change=(id:number,patch:Partial<ItemRespostaPublica>)=>setResponse(r=>r?{...r,items:r.items.map(i=>i.id===id?{...i,...patch}:i)}:r)
  const save=async(showReview=false)=>{if(!response)return;setBusy(true);setError('');try{const updated=await api<RespostaPublica>(`/public/responses/${response.responseToken}/items`,{method:'PUT',body:JSON.stringify({items:response.items.map(i=>({id:i.id,unitPrice:i.available?i.unitPrice:null,availableQuantity:i.available?i.availableQuantity:null,available:i.available,observation:i.observation}))})});setResponse(updated);setSaved(true);setTimeout(()=>setSaved(false),1800);if(showReview)setReview(true)}catch(e){setError(e instanceof ErroApi?e.message:'Não foi possível salvar.')}finally{setBusy(false)}}
  const submit=async()=>{if(!response)return;setBusy(true);setError('');try{setResponse(await api<RespostaPublica>(`/public/responses/${response.responseToken}/submit`,{method:'POST'}));setReview(false);localStorage.removeItem(`cotapreco_response_${token}`)}catch(e){setError(e instanceof ErroApi?e.message:'Não foi possível enviar.')}finally{setBusy(false)}}
  if(loading)return <div className="public-page"><Carregando/></div>;if(!quotation)return <div className="public-page public-center"><div className="public-logo"><span>C$</span>CotaPreço</div><AvisoErro message={error}/></div>
  if(response?.status==='SUBMITTED')return <div className="public-page public-center"><div className="success-icon large"><CheckCircle2/></div><span className="eyebrow green">Tudo certo!</span><h1>Cotação enviada com sucesso.</h1><p>Obrigado pela participação, {response.representativeName}. A {response.companyName} já recebeu sua proposta.</p><div className="success-receipt"><Building2/><div><span>Distribuidora</span><strong>{response.supplierName}</strong></div><Check/></div><div className="public-security"><ShieldCheck/>Sua resposta foi enviada de forma segura.</div></div>
  if(!response)return <div className="public-page"><PublicHeader/><main className="public-container"><section className="public-intro"><span className="eyebrow green">Convite para cotação</span><h1>{quotation.quotationName}</h1><p className="company-name"><Building2/>{quotation.companyName}</p><div className="public-meta"><div><ShoppingBag/><span><strong>{quotation.productCount}</strong> produtos solicitados</span></div><div><Clock3/><span><strong>Prazo</strong> {date(quotation.expiresAt)}</span></div></div>{!quotation.acceptingResponses&&<div className="alert alert-warning">Esta cotação não está mais aceitando respostas.</div>}</section><form className="public-card" onSubmit={start}><div><span className="step-pill">1</span><h2>Identifique-se para começar</h2><p>Seus dados serão vistos somente pela farmácia.</p></div>{error&&<AvisoErro message={error}/>}<label>Seu nome<input required autoComplete="name" value={identity.representativeName} onChange={e=>setIdentity({...identity,representativeName:e.target.value})} placeholder="Nome do representante"/></label><label>Distribuidora<input required value={identity.supplierName} onChange={e=>setIdentity({...identity,supplierName:e.target.value})} placeholder="Nome da distribuidora"/></label><label>Telefone<input required inputMode="tel" autoComplete="tel" value={identity.phone} onChange={e=>setIdentity({...identity,phone:e.target.value})} placeholder="(81) 99999-9999"/></label><div className="public-form-row"><label>E-mail <small>Opcional</small><input type="email" value={identity.email} onChange={e=>setIdentity({...identity,email:e.target.value})} placeholder="voce@empresa.com"/></label><label>CNPJ <small>Opcional</small><input inputMode="numeric" value={identity.supplierDocument} onChange={e=>setIdentity({...identity,supplierDocument:e.target.value})} placeholder="00.000.000/0001-00"/></label></div><button className="button button-primary button-large full-button" disabled={busy||!quotation.acceptingResponses}>{busy?'Iniciando...':<>Começar a cotar <ArrowRight/></>}</button></form></main><PublicFooter/></div>
  const quoted=response.items.filter(i=>i.available&&i.unitPrice&&i.availableQuantity);const total=quoted.reduce((sum,i)=>sum+(i.unitPrice??0)*Math.min(i.availableQuantity??0,i.requestedQuantity),0)
  if(review)return <div className="public-page"><PublicHeader/><main className="public-container quote-container"><button className="text-link" onClick={()=>setReview(false)}><ArrowLeft/>Voltar aos produtos</button><section className="public-card review-card"><div className="success-icon small-icon"><PackageCheck/></div><span className="eyebrow green">Revise antes de enviar</span><h1>Resumo da sua proposta</h1><p>Confira os valores. Após o envio, a proposta não poderá ser alterada.</p>{error&&<AvisoErro message={error}/>}<div className="review-stats"><div><span>Produtos cotados</span><strong>{quoted.length} de {response.items.length}</strong></div><div><span>Valor total</span><strong>{money(total)}</strong></div></div><div className="review-products">{quoted.map(i=><div key={i.id}><div><strong>{i.productName}</strong><span>{i.availableQuantity} un. × {money(i.unitPrice)}</span></div><strong>{money((i.unitPrice??0)*Math.min(i.availableQuantity??0,i.requestedQuantity))}</strong></div>)}</div><button className="button button-primary button-large full-button" disabled={busy} onClick={()=>void submit()}>{busy?'Enviando...':<>Confirmar e enviar cotação <Send/></>}</button><button className="button button-ghost full-button" onClick={()=>setReview(false)}>Continuar editando</button></section></main><PublicFooter/></div>
  return <div className="public-page"><PublicHeader/><main className="public-container quote-container"><section className="quote-heading"><span className="eyebrow green">{quotation.companyName}</span><h1>{quotation.quotationName}</h1><p>Informe os produtos que sua distribuidora consegue fornecer.</p><div className="progress-line"><div style={{width:`${Math.round(quoted.length/response.items.length*100)}%`}}/><span>{quoted.length} de {response.items.length} cotados</span></div></section>{error&&<AvisoErro message={error}/>}<div className="public-products">{response.items.map((item,index)=><article className={`public-product ${item.available?'available':''}`} key={item.id}><div className="product-top"><span>{index+1}</span><div><h3>{item.productName}</h3><p>GTIN {item.gtin}</p></div><strong>{item.requestedQuantity} un.</strong></div><label className="availability"><input type="checkbox" checked={item.available} onChange={e=>change(item.id,{available:e.target.checked,unitPrice:e.target.checked?item.unitPrice:null,availableQuantity:e.target.checked?(item.availableQuantity??item.requestedQuantity):null})}/><span>{item.available?'Disponível para cotar':'Marcar como disponível'}</span></label>{item.available&&<div className="price-fields"><label>Preço unitário (R$)<input type="number" inputMode="decimal" min="0.01" step="0.01" placeholder="0,00" value={item.unitPrice??''} onChange={e=>change(item.id,{unitPrice:e.target.value?Number(e.target.value):null})}/></label><label>Quantidade disponível<input type="number" inputMode="numeric" min="1" step="1" value={item.availableQuantity??''} onChange={e=>change(item.id,{availableQuantity:e.target.value?Number(e.target.value):null})}/></label><label className="full">Observação <small>Opcional</small><input maxLength={500} placeholder="Condição, validade, embalagem..." value={item.observation??''} onChange={e=>change(item.id,{observation:e.target.value})}/></label></div>}</article>)}</div><div className="public-action-bar"><div><span>{quoted.length} produtos cotados</span><strong>{money(total)}</strong></div><button className="button button-secondary" disabled={busy} onClick={()=>void save(false)}><Save/>{saved?'Salvo!':'Salvar'}</button><button className="button button-primary" disabled={busy||quoted.length===0} onClick={()=>void save(true)}>Revisar e enviar <ArrowRight/></button></div></main><PublicFooter/></div>
}
function PublicHeader(){return <header className="public-header"><div className="public-logo"><span>C$</span>CotaPreço</div><div><ShieldCheck/>Ambiente seguro</div></header>}
function PublicFooter(){return <footer className="public-footer"><ShieldCheck/>Seus preços são confidenciais e visíveis apenas para a farmácia.</footer>}
